import { Typography, Grid } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import FeaturedCard from '../components/Hero/FeatureCard'
import Footer from '../components/Footer'
import HeroSection from '../components/Hero/HeroSection'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css';
import {FaNetworkWired} from 'react-icons/fa'
import {BiCheckDouble} from 'react-icons/bi'
import {ImPieChart} from 'react-icons/im'
import FeatureExpand from '../components/Hero/FeatureExpand'
import MapImage from '../resources/images/map.png'
import StatsImage from '../resources/images/stats.png'
import GraphImage from '../resources/images/graph.png'
import BagBg from '../resources/background/bagBg.png'
import BagImage from '../resources/images/Emoji.png'
import Rplus from '../resources/images/rplus.png'
import Teesas from '../resources/images/teesas.png'
import Imose from '../resources/images/imose.png'
import Fbank from '../resources/images/first_bank.png'
import Sterling from '../resources/images/sterling_bank.png'
import Wema from '../resources/images/wema_bank.png'
import RoundedButton from '../components/Buttons/RoundedButton'
import Partners from '../components/Hero/PartenersLogo'

// import {AccountTreeIcon} from '@mui/icons-material';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-metric Suites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Navbar/> */}
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}

          <Navbar/>
          <HeroSection/>
          <Grid container justifyContent='center' my={2} md={6}>
            <Typography fontWeight={800} textAlign='center' my={2} fontSize={25}>
            Understand KPI Analytics for Productivity
            </Typography>

            <Typography fontWeight={400} textAlign='center' fontSize={17}>
            Our Simplified system helps you track, Performance measurement, Agile task planning and tracking software, Structured Appraisal and data capture. 
            </Typography>
          </Grid>

          <Grid container my={3} justifyContent='space-around'>
              <FeaturedCard
                icon={<FaNetworkWired color='#7B9AFF'/>}
                iconBg='#EDEFF1'
                title='Strategy Execution Automation'
                body='Provides a clear and compelling 
                strategic direction to your team.
                 Leverage core capabilities of the organisation.'
              />

              <FeaturedCard
                icon={<BiCheckDouble color='#F2C94C' fontWeight={800} size={28}/>}
                iconBg='#FFF2CC'
                title='Strategy Execution Automation'
                body='Provides a clear and compelling 
                strategic direction to your team.
                 Leverage core capabilities of the organisation.'
              />

              <FeaturedCard
                icon={<ImPieChart color='#963A04' size={28}/>}
                iconBg='#FFEADD'
                title='Strategy Execution Automation'
                body='Provides a clear and compelling 
                strategic direction to your team.
                 Leverage core capabilities of the organisation.'
              />
          </Grid>

          <Grid>
            <Typography fontWeight={800} textAlign='center' my={2} fontSize={25}>
              Some Features and Capabilities
            </Typography>

            <FeatureExpand 
              header='Performance Management & Assessment Data Generation Automation' 
              body='Balanced Scorecard, HR Scorecards etc.  Also, existing performance management software like the intrafocus, QPR Metrics etc.'
              image={MapImage}
              direction='ltr'
              />

              <FeatureExpand 
                header='Software Structure- Reporting Modules Human Performance Reporting' 
                body='Individual Task Rating Task assessment elements ratings like;  TAT, Quality, Quantity.
                Individual task contribution to team task which builds up into team performance. Cumulative tasks contributions to individual performance score achieved. Team overall score with all the task elements
                '
                image={StatsImage}
                direction='rtl'
              />

              <FeatureExpand 
                header='Corporate Performance Management Reporting' 
                body='Team performance Reporting with all elements captured Initiative/JD score.
                Various teams and hierarchies e.g. unit, department, group and or divisions.
                Strategic objectives score-corporate perspective grouping ratings to access performance directions. 
                '
                image={GraphImage}
                direction='ltr'
              />
          </Grid>
    
          <Grid container justifyContent='center' className={styles.artBg} py={2}>
                <Grid px={7} py={7} item className={styles.joinBg} md={7} borderRadius={2}>
                  <Grid container justifyContent='center'>
                    <Image src={BagImage}/>
                  </Grid>
                  
                <Typography fontWeight={800} textAlign='center' mx={2} my={2} fontSize={25}>
                Join the growing list of our partners across the globe.
                  </Typography>

                  <Typography fontWeight={400} textAlign='center' fontSize={17}>
                  Our Value Added members are partners that want to be part of resallers for the leading Performance Management software
                  </Typography>
                  <Grid container justifyContent='center' pt={3} >
                    <RoundedButton text='Join Now'/>
                  </Grid>
                  
              </Grid>
          </Grid>

          <Grid container justifyContent='center' my={4} px={3}>
            <Typography fontWeight={800} textAlign='center' mx={2} fontSize={25}>
              Companies we helped grow
            </Typography>
            
            <Grid container justifyContent='center' alignItems='center' md={10} px={8}>
              <Partners image={Rplus}/>
              <Partners image={Imose}/>
              <Partners image={Teesas}/>
              <Partners image={Rplus}/>
              <Partners image={Imose}/>
              <Partners image={Rplus}/>
              <Partners image={Fbank}/>
              <Partners image={Wema}/>
              <Partners image={Rplus}/>
              <Partners image={Wema}/>
              <Partners image={Sterling}/>
            </Grid>

          </Grid>
          {/* <br/> */}
          <Grid container justifyContent='center' sx={{background:`url(${BagBg})`}}>
                <Grid px={7} py={4} item sx={{ margin:'0 auto'}} className={styles.startedBg} md={10} borderRadius={2}>
                  {/* <Grid container justifyContent='center'>
                    <Image src={BagImage} style={{margin:'0 auto'}}/>
                  </Grid> */}
                  
                <Typography fontWeight={800} textAlign='center' mx={2} my={2} fontSize={25}>
                    Get Started with E-metricsuite today
                  </Typography>

                  <Typography fontWeight={400} textAlign='center' fontSize={17}>
                  Loren ipsum is simply dummy text of the  typesetting industry, it’s very popular in the design world...
                  </Typography>
                  <Grid container justifyContent='center' pt={3} >
                    <RoundedButton text='Get Started'/>
                  </Grid>
                  
              </Grid>
          </Grid>
      </main>

      {/* <footer className={styles.footer}> */}
        <Footer/>
      {/* </footer> */}
    </div>
  )
}
